# Generated by Django 3.0.4 on 2020-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destinations_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('city', models.CharField(default='miasto', max_length=100)),
                ('street', models.CharField(default='ulica', max_length=100)),
                ('voivodeship', models.CharField(default='wojewodztwo', max_length=100)),
                ('price', models.IntegerField(default='0')),
                ('desc', models.TextField(default='')),
                ('img', models.ImageField(upload_to='pics')),
                ('duration', models.IntegerField(default=0)),
                ('num_people', models.IntegerField(default=1)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(default='brak nazwy', max_length=100)),
                ('city', models.CharField(default='miasto', max_length=100)),
                ('voivodeship', models.CharField(default='brak danych', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
